image: docker:latest
services:
  - docker:dind

stages:
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: package
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
      - target/*.tar

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
  - kubectl delete -f k8s-deploy.yaml
  - kubectl apply -f k8s-deploy.yaml

