image: docker:latest
services:
  - docker:dind

stages:
  - package
#  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: package
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
      - target/*.tar

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
  - kubectl delete secret registry.gitlab-ce
  - kubectl create secret docker-registry registry.gitlab-ce --docker-server=http://gitlab-ce:5050 --docker-username=infoplus --docker-password=$REGISTRY_PASSWD --docker-email=infoplus@gitlab-ce
  - kubectl apply -f k8s-deploy.yaml

